name: Example 1
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  TAG_NAME: "tag_${{ github.sha }}_${{ github.run_attempt }}"
jobs:
  example1:
    name: Example 1
    runs-on: ubuntu-latest
    run: |
      git push https://${{ secrets.GITHUB_TOKEN }}@${{ github.repository }} ${{ env.TAG_NAME }} -m "Automated!"
