name: Example 1 Workflow
on:
  push:
  workflow_dispatch:
env:
  TAG_NAME: "tag_${{ github.sha }}_${{ github.run_attempt }}"
jobs:
  example1:
    name: Example 1 Job
    runs-on: ubuntu-latest
    steps:
    - name: Example 1 Action
      run: echo ${{ github.repository }} ${{ env.TAG_NAME }}
